---
name: Test Packages
on:
  pull_request:
jobs:
  testall:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: setup
        shell: powershell
        run: |
          $profileInstall = @'
          # Chocolatey profile
          $ChocolateyProfile = "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          if (Test-Path($ChocolateyProfile)) {
              Import-Module "$ChocolateyProfile"
          }
          '@

          $profilePath = Split-Path -parent $profile 
          New-Item $profilePath -ItemType Directory
          $profileInstall | Out-File $profile
          ./setup/au_setup.ps1
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
      - run: ./test_all.ps1
        shell: powershell
        env:
          github_user_repo: ${{ env.GITHUB_REPOSITORY }}
      - run: |
          Get-Content -Path "Update-Force-Test-.md" | Out-File -FilePath "$env:GITHUB_STEP_SUMMARY" -Append
