---
name: Run Updates
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 16 * * 1-5"
  workflow_dispatch:
permissions: 
    contents: write
jobs:
  updateall:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: setup
        shell: powershell
        run: |
          $profileInstall = @'
          # Chocolatey profile
          $ChocolateyProfile = "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          if (Test-Path($ChocolateyProfile)) {
              Import-Module "$ChocolateyProfile"
          }
          '@

          $profilePath = Split-Path -parent $profile 
          New-Item $profilePath -ItemType Directory
          $profileInstall | Out-File $profile
          ./setup/au_setup.ps1
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
      - run: ./update_all.ps1
        shell: powershell
        env:
          au_Push: true
          github_user_repo: ${{ env.GITHUB_REPOSITORY }}
          github_api_key: ${{ secrets.GITHUB_TOKEN }}
          api_key: ${{ secrets.CHOCO_API_KEY }}
      - run: |
          Get-Content -Path "Update-AUPackages.md" | Out-File -FilePath "$env:GITHUB_STEP_SUMMARY" -Append
