---
name: Run Updates
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 16 * * 1-5"
permissions: 
    contents: write
jobs:
  updateall:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: setup
        shell: powershell
        run: |
          $profileInstall = @'
          # Chocolatey profile
          $ChocolateyProfile = "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
          if (Test-Path($ChocolateyProfile)) {
              Import-Module "$ChocolateyProfile"
          }
          '@

          $profilePath = Split-Path -parent $profile 
          New-Item $profilePath -ItemType Directory
          $profileInstall | Out-File $profile
          ./setup/au_setup.ps1
      - run: ./update_all.ps1
        shell: powershell
        env:
          au_Push: true
          github_user_repo: ${{ env.GITHUB_REPOSITORY }}
          github_api_key: ${{ secrets.GITHUB_TOKEN }}
          api_key: ${{ secrets.CHOCO_API_KEY }}
      - uses: actions/upload-artifact@v4
        with:
          name: run
          path: |
            update_info.xml
            Update-AUPackages.md
            Update-History.md
